mutation updateGraduationGQL (
    $gradId: Int
  	$brandiId: Int
    $gradDate: DateTime
    ){
  updateGraduation (input:{
    gradId: $gradId
    brandiId: $brandiId
    gradDate: $gradDate
  }) {
    graduation {
    	gradId
        brandiId
        gradDate
    }
  }
}